import React from 'react'
import { render } from 'react-dom'
import { createStore } from 'redux'
import { Provider } from 'react-redux'
import FlinkGraph from './FlinkGraph'
import rootReducer from './reducers'

const store = createStore(rootReducer)
const jobDetailCorrect = {
    "verticesDetail": {
    "vertices":[
        {
            "id":"cbc357ccb763df2852fee8c4fc7d55f2",
            "name":"Source: UmsKafka010TableSource(creat_time, spread_source, last_update_time, phone_number, id, status) -> SourceConversion(table:[builtin, default, t_user_info, source: [UmsKafka010TableSource(creat_time, spread_source, last_update_time, phone_number, id, status)]], fields:(creat_time, spread_source, last_update_time, phone_number, id, status)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(select: (id, phone_number, creat_time, status))",
            "parallelism":1,
            "subtask_metrics":[
                {
                    "numBytesInLocal":"0",
                    "numBytesInRemotePerSecond":"0.0",
                    "waitOutput.histogram_max":"0",
                    "waitOutput.histogram_stddev":"0.0",
                    "numBytesOut":"7045120",
                    "waitOutput.histogram_median":"0.0",
                    "waitOutput.count":"0",
                    "cbc357ccb763df2852fee8c4fc7d55f2.numRecordsOutOperator":"108746",
                    "cbc357ccb763df2852fee8c4fc7d55f2.numRecordsInOperator":"0",
                    "waitOutput.histogram_p999":"0.0",
                    "7f56ab457a950ae965a379e2699378b9.numRecordsInOperator":"108746",
                    "7f56ab457a950ae965a379e2699378b9.numRecordsOutOperator":"108746",
                    "numRecordsOut":"108746",
                    "numBuffersOut":"215",
                    "buffers.inputQueueLength":"0",
                    "numBytesOutPerSecond":"0.0",
                    "be96413273c1f665c3d8afa79728dcb9.numRecordsOutOperator":"108746",
                    "waitOutput.histogram_p90":"0.0",
                    "waitOutput.histogram_p75":"0.0",
                    "waitOutput.histogram_p95":"0.0",
                    "numRecordsIn":"0",
                    "buffers.outputQueueLength":"1",
                    "waitOutput.histogram_min":"0",
                    "0099930c6a059f9143d022038467b313.numRecordsInOperator":"108746",
                    "0099930c6a059f9143d022038467b313.numRecordsOutOperator":"108746",
                    "waitOutput.histogram_p99":"0.0",
                    "waitOutput.histogram_p98":"0.0",
                    "numBytesInLocalPerSecond":"0.0",
                    "waitOutput.histogram_mean":"0.0",
                    "numRecordsOutPerSecond":"0.0",
                    "buffers.inPoolUsage":"0.0",
                    "be96413273c1f665c3d8afa79728dcb9.numRecordsInOperator":"108746",
                    "buffers.outPoolUsage":"0.1",
                    "waitOutput.sum":"0.0",
                    "numRecordsInPerSecond":"0.0",
                    "numBytesInRemote":"0"
                }
            ],
            "metrics":{
                "read-bytes":0,
                "read-bytes-complete":true,
                "write-bytes":7045120,
                "write-bytes-complete":true,
                "read-records":0,
                "read-records-complete":true,
                "write-records":108746,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"6cdc5bb954874d922eaee11a8e7b5dd5",
            "name":"Source: UmsKafka010TableSource(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id) -> SourceConversion(table:[builtin, default, t_customer_info, source: [UmsKafka010TableSource(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id)]], fields:(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(where: ((CAST(is_deleted) = 0) AND user_id IS NOT NULL), select: (user_id, customer_id, spread_source, remark_name))",
            "parallelism":1,
            "subtask_metrics":[
                {
                    "numBytesInLocal":"0",
                    "numBytesInRemotePerSecond":"0.0",
                    "waitOutput.histogram_max":"0",
                    "waitOutput.histogram_stddev":"0.0",
                    "numBytesOut":"3735552",
                    "waitOutput.histogram_median":"0.0",
                    "waitOutput.count":"0",
                    "6cdc5bb954874d922eaee11a8e7b5dd5.numRecordsInOperator":"0",
                    "326f5d72e3c2c200469c01665ae0af71.numRecordsOutOperator":"86765",
                    "waitOutput.histogram_p999":"0.0",
                    "e87f8b3ef92a3a5cc18da5b311ec081b.numRecordsOutOperator":"76400",
                    "a70537a881dc48c52833ffd2434b4ec8.numRecordsOutOperator":"86765",
                    "numRecordsOut":"76400",
                    "numBuffersOut":"114",
                    "a70537a881dc48c52833ffd2434b4ec8.numRecordsInOperator":"86765",
                    "buffers.inputQueueLength":"0",
                    "numBytesOutPerSecond":"0.0",
                    "waitOutput.histogram_p90":"0.0",
                    "waitOutput.histogram_p75":"0.0",
                    "326f5d72e3c2c200469c01665ae0af71.numRecordsInOperator":"86765",
                    "waitOutput.histogram_p95":"0.0",
                    "numRecordsIn":"0",
                    "buffers.outputQueueLength":"1",
                    "6cdc5bb954874d922eaee11a8e7b5dd5.numRecordsOutOperator":"86765",
                    "waitOutput.histogram_min":"0",
                    "waitOutput.histogram_p99":"0.0",
                    "waitOutput.histogram_p98":"0.0",
                    "numBytesInLocalPerSecond":"0.0",
                    "waitOutput.histogram_mean":"0.0",
                    "numRecordsOutPerSecond":"0.0",
                    "buffers.inPoolUsage":"0.0",
                    "e87f8b3ef92a3a5cc18da5b311ec081b.numRecordsInOperator":"86765",
                    "buffers.outPoolUsage":"0.1",
                    "waitOutput.sum":"0.0",
                    "numRecordsInPerSecond":"0.0",
                    "numBytesInRemote":"0"
                }
            ],
            "metrics":{
                "read-bytes":0,
                "read-bytes-complete":true,
                "write-bytes":3735552,
                "write-bytes-complete":true,
                "read-records":0,
                "read-records-complete":true,
                "write-records":76400,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"2963852293169ba90d9d1e7d6308db5c",
            "name":"Source: UmsKafka010TableSource(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id) -> SourceConversion(table:[builtin, default, t_customer_assistant_relation, source: [UmsKafka010TableSource(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id)]], fields:(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(where: ((CAST(is_deleted) = 0) AND student_id IS NOT NULL), select: (student_id, CAST(assistant_id) AS assistant_id))",
            "parallelism":1,
            "subtask_metrics":[
                {
                    "numBytesInLocal":"0",
                    "numBytesInRemotePerSecond":"0.0",
                    "waitOutput.histogram_max":"0",
                    "waitOutput.histogram_stddev":"0.0",
                    "numBytesOut":"1245184",
                    "f3fa23a9fd63123f1647fc4acfb0afa9.numRecordsInOperator":"62650",
                    "waitOutput.histogram_median":"0.0",
                    "waitOutput.count":"0",
                    "waitOutput.histogram_p999":"0.0",
                    "659fef941cf770e4966beac1eeb35374.numRecordsOutOperator":"62650",
                    "numRecordsOut":"38381",
                    "numBuffersOut":"38",
                    "buffers.inputQueueLength":"0",
                    "a0a665132e00786f5f9734095ae0ec4d.numRecordsInOperator":"62650",
                    "numBytesOutPerSecond":"0.0",
                    "waitOutput.histogram_p90":"0.0",
                    "waitOutput.histogram_p75":"0.0",
                    "waitOutput.histogram_p95":"0.0",
                    "numRecordsIn":"0",
                    "buffers.outputQueueLength":"1",
                    "waitOutput.histogram_min":"0",
                    "waitOutput.histogram_p99":"0.0",
                    "waitOutput.histogram_p98":"0.0",
                    "a0a665132e00786f5f9734095ae0ec4d.numRecordsOutOperator":"38381",
                    "659fef941cf770e4966beac1eeb35374.numRecordsInOperator":"62650",
                    "numBytesInLocalPerSecond":"0.0",
                    "waitOutput.histogram_mean":"0.0",
                    "numRecordsOutPerSecond":"0.0",
                    "buffers.inPoolUsage":"0.0",
                    "2963852293169ba90d9d1e7d6308db5c.numRecordsOutOperator":"62650",
                    "f3fa23a9fd63123f1647fc4acfb0afa9.numRecordsOutOperator":"62650",
                    "buffers.outPoolUsage":"0.1",
                    "waitOutput.sum":"0.0",
                    "numRecordsInPerSecond":"0.0",
                    "2963852293169ba90d9d1e7d6308db5c.numRecordsInOperator":"0",
                    "numBytesInRemote":"0"
                }
            ],
            "metrics":{
                "read-bytes":0,
                "read-bytes-complete":true,
                "write-bytes":1245184,
                "write-bytes-complete":true,
                "read-records":0,
                "read-records-complete":true,
                "write-records":38381,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"edff7340c63af0cafbf43d7dda52199d",
            "name":"GroupAggregate(groupBy: (user_id, customer_id), select: (user_id, customer_id, MAX(spread_source) AS spread_source, MAX(remark_name) AS remark_name))",
            "parallelism":1,
            "subtask_metrics":[
                {
                    "numBytesInLocal":"0",
                    "checkpointAlignmentTime":"0",
                    "numBytesInRemotePerSecond":"0.0",
                    "waitOutput.histogram_max":"0",
                    "waitOutput.histogram_stddev":"0.0",
                    "numBytesOut":"3735552",
                    "waitOutput.histogram_median":"0.0",
                    "waitOutput.count":"0",
                    "currentInputWatermark":"1560504717000",
                    "waitOutput.histogram_p999":"0.0",
                    "edff7340c63af0cafbf43d7dda52199d.numRecordsOutOperator":"76393",
                    "numRecordsOut":"76393",
                    "numBuffersOut":"114",
                    "buffers.inputQueueLength":"0",
                    "edff7340c63af0cafbf43d7dda52199d.numRecordsInOperator":"76400",
                    "numBytesOutPerSecond":"0.0",
                    "waitOutput.histogram_p90":"0.0",
                    "waitOutput.histogram_p75":"0.0",
                    "waitOutput.histogram_p95":"0.0",
                    "numRecordsIn":"76400",
                    "buffers.outputQueueLength":"1",
                    "waitOutput.histogram_min":"0",
                    "waitOutput.histogram_p99":"0.0",
                    "waitOutput.histogram_p98":"0.0",
                    "numBytesInLocalPerSecond":"0.0",
                    "waitOutput.histogram_mean":"0.0",
                    "numRecordsOutPerSecond":"0.0",
                    "buffers.inPoolUsage":"0.125",
                    "buffers.outPoolUsage":"0.1",
                    "waitOutput.sum":"0.0",
                    "numRecordsInPerSecond":"0.0",
                    "numBytesInRemote":"3756178"
                }
            ],
            "metrics":{
                "read-bytes":3756178,
                "read-bytes-complete":true,
                "write-bytes":3735552,
                "write-bytes-complete":true,
                "read-records":76400,
                "read-records-complete":true,
                "write-records":76393,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0.125,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"dc84cce8187b24c5fc99ebc698f3e3f7",
            "name":"LeftOuterJoin(where: (=(id, user_id)), join: (id, phone_number, creat_time, status, user_id, customer_id, spread_source, remark_name)) -> Calc(select: (id, phone_number, creat_time, status, customer_id, spread_source, remark_name))",
            "parallelism":1,
            "subtask_metrics":[
                {
                    "numBytesInLocal":"0",
                    "checkpointAlignmentTime":"0",
                    "numBytesInRemotePerSecond":"0.0",
                    "waitOutput.histogram_max":"0",
                    "waitOutput.histogram_stddev":"0.0",
                    "numBytesOut":"11927552",
                    "waitOutput.histogram_median":"0.0",
                    "waitOutput.count":"0",
                    "currentInputWatermark":"1560149999000",
                    "waitOutput.histogram_p999":"0.0",
                    "numRecordsOut":"133880",
                    "dc84cce8187b24c5fc99ebc698f3e3f7.numRecordsInOperator":"185139",
                    "numBuffersOut":"364",
                    "buffers.inputQueueLength":"0",
                    "numBytesOutPerSecond":"0.0",
                    "waitOutput.histogram_p90":"0.0",
                    "waitOutput.histogram_p75":"0.0",
                    "waitOutput.histogram_p95":"0.0",
                    "numRecordsIn":"185139",
                    "buffers.outputQueueLength":"1",
                    "waitOutput.histogram_min":"0",
                    "d03530502eaa1f0b8fad8ac073cccc1f.numRecordsInOperator":"133880",
                    "waitOutput.histogram_p99":"0.0",
                    "waitOutput.histogram_p98":"0.0",
                    "numBytesInLocalPerSecond":"0.0",
                    "waitOutput.histogram_mean":"0.0",
                    "numRecordsOutPerSecond":"0.0",
                    "buffers.inPoolUsage":"0.125",
                    "buffers.outPoolUsage":"0.1",
                    "d03530502eaa1f0b8fad8ac073cccc1f.numRecordsOutOperator":"133880",
                    "waitOutput.sum":"0.0",
                    "numRecordsInPerSecond":"0.0",
                    "dc84cce8187b24c5fc99ebc698f3e3f7.numRecordsOutOperator":"133880",
                    "numBytesInRemote":"10824265"
                }
            ],
            "metrics":{
                "read-bytes":10824265,
                "read-bytes-complete":true,
                "write-bytes":11927552,
                "write-bytes-complete":true,
                "read-records":185139,
                "read-records-complete":true,
                "write-records":133880,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0.125,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"f8543e3639e7b3e505fe052f4d476c57",
            "name":"LeftOuterJoin(where: (=(id, student_id)), join: (id, phone_number, creat_time, status, customer_id, spread_source, remark_name, student_id, assistant_id)) -> Calc(select: (id AS user_id, phone_number AS body.phone_num, creat_time AS body.create_time, status AS body.status, customer_id AS body.customer_id, spread_source AS body.spread_source, remark_name AS body.remark_name, assistant_id AS body.assistant_id)) -> SinkConversion to Tuple2 -> Sink: HBase143Writer-> table:flink:olap_rt_student_real_time_static_test schema:{HBaseTableSchemaV2{ rowKeyName='user_id', rowKeyType=Long, charset=UTF-8, familySchema=body:phone_num|String, body:create_time|Timestamp, body:status|Integer, body:customer_id|Long, body:spread_source|String, body:remark_name|String, body:assistant_id|String}}",
            "parallelism":1,
            "subtask_metrics":[
                {
                    "numBytesInLocal":"1266693",
                    "checkpointAlignmentTime":"0",
                    "numBytesInRemotePerSecond":"0.0",
                    "waitOutput.histogram_max":"0",
                    "ea48fd159f2a8f8a682ac7e50a3cccec.numRecordsInOperator":"134050",
                    "waitOutput.histogram_stddev":"0.0",
                    "a64439c7484a0ab4fe57983368e929a0.numRecordsOutOperator":"134050",
                    "3767294c81a65b93182b6d5a39ee2b05.numRecordsOutOperator":"134050",
                    "numBytesOut":"0",
                    "a64439c7484a0ab4fe57983368e929a0.numRecordsInOperator":"134050",
                    "3767294c81a65b93182b6d5a39ee2b05.numRecordsInOperator":"134050",
                    "waitOutput.histogram_median":"0.0",
                    "waitOutput.count":"0",
                    "currentInputWatermark":"1559026741000",
                    "waitOutput.histogram_p999":"0.0",
                    "numRecordsOut":"0",
                    "numBuffersOut":"0",
                    "ea48fd159f2a8f8a682ac7e50a3cccec.numRecordsOutOperator":"0",
                    "buffers.inputQueueLength":"0",
                    "numBytesOutPerSecond":"0.0",
                    "waitOutput.histogram_p90":"0.0",
                    "waitOutput.histogram_p75":"0.0",
                    "waitOutput.histogram_p95":"0.0",
                    "numRecordsIn":"172261",
                    "buffers.outputQueueLength":"0",
                    "waitOutput.histogram_min":"0",
                    "f8543e3639e7b3e505fe052f4d476c57.numRecordsInOperator":"172261",
                    "waitOutput.histogram_p99":"0.0",
                    "waitOutput.histogram_p98":"0.0",
                    "f8543e3639e7b3e505fe052f4d476c57.numRecordsOutOperator":"134050",
                    "numBytesInLocalPerSecond":"0.0",
                    "waitOutput.histogram_mean":"0.0",
                    "numRecordsOutPerSecond":"0.0",
                    "buffers.inPoolUsage":"0.125",
                    "buffers.outPoolUsage":"0.0",
                    "waitOutput.sum":"0.0",
                    "numRecordsInPerSecond":"0.0",
                    "numBytesInRemote":"11929570"
                }
            ],
            "metrics":{
                "read-bytes":13196263,
                "read-bytes-complete":true,
                "write-bytes":0,
                "write-bytes-complete":true,
                "read-records":172261,
                "read-records-complete":true,
                "write-records":0,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0.125,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        }
    ],
    "operators":[
        {
            "vertex_id":"cbc357ccb763df2852fee8c4fc7d55f2",
            "operator_id":"0099930c6a059f9143d022038467b313",
            "name":"Calc(select: (id, phone_number, creat_time, status))",
            "inputs":[
                {
                    "operator_id":"7f56ab457a950ae965a379e2699378b9",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"Calc(select__(id__phone_number__creat_time__status))"
        },
        {
            "vertex_id":"cbc357ccb763df2852fee8c4fc7d55f2",
            "operator_id":"7f56ab457a950ae965a379e2699378b9",
            "name":"WatermarkAssigner(rowtime: last_update_time, offset: 4000)",
            "inputs":[
                {
                    "operator_id":"be96413273c1f665c3d8afa79728dcb9",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"WatermarkAssigner(rowtime__last_update_time__offset__4000)"
        },
        {
            "vertex_id":"cbc357ccb763df2852fee8c4fc7d55f2",
            "operator_id":"be96413273c1f665c3d8afa79728dcb9",
            "name":"SourceConversion(table:[builtin, default, t_user_info, source: [UmsKafka010TableSource(creat_time, spread_source, last_update_time, phone_number, id, status)]], fields:(creat_time, spread_source, last_update_time, phone_number, id, status))",
            "inputs":[
                {
                    "operator_id":"cbc357ccb763df2852fee8c4fc7d55f2",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"SourceConversion(table_[builtin__default__t_user_info__source__[UmsKafka010Table"
        },
        {
            "vertex_id":"cbc357ccb763df2852fee8c4fc7d55f2",
            "operator_id":"cbc357ccb763df2852fee8c4fc7d55f2",
            "name":"Source: UmsKafka010TableSource(creat_time, spread_source, last_update_time, phone_number, id, status)",
            "inputs":[

            ],
            "metric_name":"Source__UmsKafka010TableSource(creat_time__spread_source__last_update_time__phon"
        },
        {
            "vertex_id":"6cdc5bb954874d922eaee11a8e7b5dd5",
            "operator_id":"e87f8b3ef92a3a5cc18da5b311ec081b",
            "name":"Calc(where: ((CAST(is_deleted) = 0) AND user_id IS NOT NULL), select: (user_id, customer_id, spread_source, remark_name))",
            "inputs":[
                {
                    "operator_id":"326f5d72e3c2c200469c01665ae0af71",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"Calc(where__((CAST(is_deleted)_=_0)_AND_user_id_IS_NOT_NULL)__select__(user_id__"
        },
        {
            "vertex_id":"6cdc5bb954874d922eaee11a8e7b5dd5",
            "operator_id":"326f5d72e3c2c200469c01665ae0af71",
            "name":"WatermarkAssigner(rowtime: last_update_time, offset: 4000)",
            "inputs":[
                {
                    "operator_id":"a70537a881dc48c52833ffd2434b4ec8",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"WatermarkAssigner(rowtime__last_update_time__offset__4000)"
        },
        {
            "vertex_id":"6cdc5bb954874d922eaee11a8e7b5dd5",
            "operator_id":"a70537a881dc48c52833ffd2434b4ec8",
            "name":"SourceConversion(table:[builtin, default, t_customer_info, source: [UmsKafka010TableSource(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id)]], fields:(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id))",
            "inputs":[
                {
                    "operator_id":"6cdc5bb954874d922eaee11a8e7b5dd5",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"SourceConversion(table_[builtin__default__t_customer_info__source__[UmsKafka010T"
        },
        {
            "vertex_id":"6cdc5bb954874d922eaee11a8e7b5dd5",
            "operator_id":"6cdc5bb954874d922eaee11a8e7b5dd5",
            "name":"Source: UmsKafka010TableSource(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id)",
            "inputs":[

            ],
            "metric_name":"Source__UmsKafka010TableSource(is_deleted__create_time__spread_source__last_upda"
        },
        {
            "vertex_id":"2963852293169ba90d9d1e7d6308db5c",
            "operator_id":"a0a665132e00786f5f9734095ae0ec4d",
            "name":"Calc(where: ((CAST(is_deleted) = 0) AND student_id IS NOT NULL), select: (student_id, CAST(assistant_id) AS assistant_id))",
            "inputs":[
                {
                    "operator_id":"f3fa23a9fd63123f1647fc4acfb0afa9",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"Calc(where__((CAST(is_deleted)_=_0)_AND_student_id_IS_NOT_NULL)__select__(studen"
        },
        {
            "vertex_id":"2963852293169ba90d9d1e7d6308db5c",
            "operator_id":"f3fa23a9fd63123f1647fc4acfb0afa9",
            "name":"WatermarkAssigner(rowtime: last_update_time, offset: 4000)",
            "inputs":[
                {
                    "operator_id":"659fef941cf770e4966beac1eeb35374",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"WatermarkAssigner(rowtime__last_update_time__offset__4000)"
        },
        {
            "vertex_id":"2963852293169ba90d9d1e7d6308db5c",
            "operator_id":"659fef941cf770e4966beac1eeb35374",
            "name":"SourceConversion(table:[builtin, default, t_customer_assistant_relation, source: [UmsKafka010TableSource(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id)]], fields:(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id))",
            "inputs":[
                {
                    "operator_id":"2963852293169ba90d9d1e7d6308db5c",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"SourceConversion(table_[builtin__default__t_customer_assistant_relation__source_"
        },
        {
            "vertex_id":"2963852293169ba90d9d1e7d6308db5c",
            "operator_id":"2963852293169ba90d9d1e7d6308db5c",
            "name":"Source: UmsKafka010TableSource(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id)",
            "inputs":[

            ],
            "metric_name":"Source__UmsKafka010TableSource(last_update_time__assistant_id__is_deleted__creat"
        },
        {
            "vertex_id":"edff7340c63af0cafbf43d7dda52199d",
            "operator_id":"edff7340c63af0cafbf43d7dda52199d",
            "name":"GroupAggregate(groupBy: (user_id, customer_id), select: (user_id, customer_id, MAX(spread_source) AS spread_source, MAX(remark_name) AS remark_name))",
            "inputs":[
                {
                    "operator_id":"e87f8b3ef92a3a5cc18da5b311ec081b",
                    "partitioner":"HASH",
                    "type_number":0
                }
            ],
            "metric_name":"GroupAggregate(groupBy__(user_id__customer_id)__select__(user_id__customer_id__M"
        },
        {
            "vertex_id":"dc84cce8187b24c5fc99ebc698f3e3f7",
            "operator_id":"d03530502eaa1f0b8fad8ac073cccc1f",
            "name":"Calc(select: (id, phone_number, creat_time, status, customer_id, spread_source, remark_name))",
            "inputs":[
                {
                    "operator_id":"dc84cce8187b24c5fc99ebc698f3e3f7",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"Calc(select__(id__phone_number__creat_time__status__customer_id__spread_source__"
        },
        {
            "vertex_id":"dc84cce8187b24c5fc99ebc698f3e3f7",
            "operator_id":"dc84cce8187b24c5fc99ebc698f3e3f7",
            "name":"LeftOuterJoin(where: (=(id, user_id)), join: (id, phone_number, creat_time, status, user_id, customer_id, spread_source, remark_name))",
            "inputs":[
                {
                    "operator_id":"0099930c6a059f9143d022038467b313",
                    "partitioner":"HASH",
                    "type_number":1
                },
                {
                    "operator_id":"edff7340c63af0cafbf43d7dda52199d",
                    "partitioner":"HASH",
                    "type_number":2
                }
            ],
            "metric_name":"LeftOuterJoin(where__(=(id__user_id))__join__(id__phone_number__creat_time__stat"
        },
        {
            "vertex_id":"f8543e3639e7b3e505fe052f4d476c57",
            "operator_id":"ea48fd159f2a8f8a682ac7e50a3cccec",
            "name":"Sink: HBase143Writer-> table:flink:olap_rt_student_real_time_static_test schema:{HBaseTableSchemaV2{ rowKeyName='user_id', rowKeyType=Long, charset=UTF-8, familySchema=body:phone_num|String, body:create_time|Timestamp, body:status|Integer, body:customer_id|Long, body:spread_source|String, body:remark_name|String, body:assistant_id|String}}",
            "inputs":[
                {
                    "operator_id":"a64439c7484a0ab4fe57983368e929a0",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"Sink__HBase143Writer->_table_flink_olap_rt_student_real_time_static_test_schema_"
        },
        {
            "vertex_id":"f8543e3639e7b3e505fe052f4d476c57",
            "operator_id":"a64439c7484a0ab4fe57983368e929a0",
            "name":"SinkConversion to Tuple2",
            "inputs":[
                {
                    "operator_id":"3767294c81a65b93182b6d5a39ee2b05",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"SinkConversion_to_Tuple2"
        },
        {
            "vertex_id":"f8543e3639e7b3e505fe052f4d476c57",
            "operator_id":"3767294c81a65b93182b6d5a39ee2b05",
            "name":"Calc(select: (id AS user_id, phone_number AS body.phone_num, creat_time AS body.create_time, status AS body.status, customer_id AS body.customer_id, spread_source AS body.spread_source, remark_name AS body.remark_name, assistant_id AS body.assistant_id))",
            "inputs":[
                {
                    "operator_id":"f8543e3639e7b3e505fe052f4d476c57",
                    "partitioner":"FORWARD",
                    "type_number":0
                }
            ],
            "metric_name":"Calc(select__(id_AS_user_id__phone_number_AS_body_phone_num__creat_time_AS_body_"
        },
        {
            "vertex_id":"f8543e3639e7b3e505fe052f4d476c57",
            "operator_id":"f8543e3639e7b3e505fe052f4d476c57",
            "name":"LeftOuterJoin(where: (=(id, student_id)), join: (id, phone_number, creat_time, status, customer_id, spread_source, remark_name, student_id, assistant_id))",
            "inputs":[
                {
                    "operator_id":"d03530502eaa1f0b8fad8ac073cccc1f",
                    "partitioner":"HASH",
                    "type_number":1
                },
                {
                    "operator_id":"a0a665132e00786f5f9734095ae0ec4d",
                    "partitioner":"HASH",
                    "type_number":2
                }
            ],
            "metric_name":"LeftOuterJoin(where__(=(id__student_id))__join__(id__phone_number__creat_time__s"
        }
    ]
},
    "jid":"40d2c6dbe0d579018698c7e20e6ace1e",
    "name":"olap_rt_student_real_time_static_test",
    "isStoppable":false,
    "state":"RUNNING",
    "start-time":1560934186164,
    "end-time":-1,
    "duration":78708940,
    "now":1561012895104,
    "timestamps":{
        "FAILING":0,
        "RESTARTING":0,
        "RECONCILING":0,
        "CANCELED":0,
        "CREATED":1560934186164,
        "SUSPENDING":0,
        "SUSPENDED":0,
        "FAILED":0,
        "CANCELLING":0,
        "FINISHED":0,
        "RUNNING":1560934186313
    },
    "vertices":[
        {
            "id":"cbc357ccb763df2852fee8c4fc7d55f2",
            "name":"Source: UmsKafka010TableSource(creat_time, spread_source, last_update_time, phone_number, id, status) -> SourceConversion(table:[builtin, default, t_user_info, source: [UmsKafka010TableSource(creat_time, spread_source, last_update_time, phone_number, id, status)]], fields:(creat_time, spread_source, last_update_time, phone_number, id, status)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(select: (id, phone_number, creat_time, status))",
            "parallelism":1,
            "status":"RUNNING",
            "start-time":1560934281595,
            "end-time":-1,
            "duration":78613509,
            "tasks":{
                "CREATED":0,
                "CANCELING":0,
                "DEPLOYING":0,
                "FINISHED":0,
                "RECONCILING":0,
                "FAILED":0,
                "SCHEDULED":0,
                "CANCELED":0,
                "RUNNING":1
            },
            "metrics":{
                "read-bytes":0,
                "read-bytes-complete":true,
                "write-bytes":7045120,
                "write-bytes-complete":true,
                "read-records":0,
                "read-records-complete":true,
                "write-records":108746,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"6cdc5bb954874d922eaee11a8e7b5dd5",
            "name":"Source: UmsKafka010TableSource(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id) -> SourceConversion(table:[builtin, default, t_customer_info, source: [UmsKafka010TableSource(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id)]], fields:(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(where: ((CAST(is_deleted) = 0) AND user_id IS NOT NULL), select: (user_id, customer_id, spread_source, remark_name))",
            "parallelism":1,
            "status":"RUNNING",
            "start-time":1560934281604,
            "end-time":-1,
            "duration":78613500,
            "tasks":{
                "CREATED":0,
                "CANCELING":0,
                "DEPLOYING":0,
                "FINISHED":0,
                "RECONCILING":0,
                "FAILED":0,
                "SCHEDULED":0,
                "CANCELED":0,
                "RUNNING":1
            },
            "metrics":{
                "read-bytes":0,
                "read-bytes-complete":true,
                "write-bytes":3735552,
                "write-bytes-complete":true,
                "read-records":0,
                "read-records-complete":true,
                "write-records":76400,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"2963852293169ba90d9d1e7d6308db5c",
            "name":"Source: UmsKafka010TableSource(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id) -> SourceConversion(table:[builtin, default, t_customer_assistant_relation, source: [UmsKafka010TableSource(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id)]], fields:(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(where: ((CAST(is_deleted) = 0) AND student_id IS NOT NULL), select: (student_id, CAST(assistant_id) AS assistant_id))",
            "parallelism":1,
            "status":"RUNNING",
            "start-time":1560934281604,
            "end-time":-1,
            "duration":78613500,
            "tasks":{
                "CREATED":0,
                "CANCELING":0,
                "DEPLOYING":0,
                "FINISHED":0,
                "RECONCILING":0,
                "FAILED":0,
                "SCHEDULED":0,
                "CANCELED":0,
                "RUNNING":1
            },
            "metrics":{
                "read-bytes":0,
                "read-bytes-complete":true,
                "write-bytes":1245184,
                "write-bytes-complete":true,
                "read-records":0,
                "read-records-complete":true,
                "write-records":38381,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"edff7340c63af0cafbf43d7dda52199d",
            "name":"GroupAggregate(groupBy: (user_id, customer_id), select: (user_id, customer_id, MAX(spread_source) AS spread_source, MAX(remark_name) AS remark_name))",
            "parallelism":1,
            "status":"RUNNING",
            "start-time":1560934281605,
            "end-time":-1,
            "duration":78613499,
            "tasks":{
                "CREATED":0,
                "CANCELING":0,
                "DEPLOYING":0,
                "FINISHED":0,
                "RECONCILING":0,
                "FAILED":0,
                "SCHEDULED":0,
                "CANCELED":0,
                "RUNNING":1
            },
            "metrics":{
                "read-bytes":3756178,
                "read-bytes-complete":true,
                "write-bytes":3735552,
                "write-bytes-complete":true,
                "read-records":76400,
                "read-records-complete":true,
                "write-records":76393,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0.125,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"dc84cce8187b24c5fc99ebc698f3e3f7",
            "name":"LeftOuterJoin(where: (=(id, user_id)), join: (id, phone_number, creat_time, status, user_id, customer_id, spread_source, remark_name)) -> Calc(select: (id, phone_number, creat_time, status, customer_id, spread_source, remark_name))",
            "parallelism":1,
            "status":"RUNNING",
            "start-time":1560934281605,
            "end-time":-1,
            "duration":78613499,
            "tasks":{
                "CREATED":0,
                "CANCELING":0,
                "DEPLOYING":0,
                "FINISHED":0,
                "RECONCILING":0,
                "FAILED":0,
                "SCHEDULED":0,
                "CANCELED":0,
                "RUNNING":1
            },
            "metrics":{
                "read-bytes":10824265,
                "read-bytes-complete":true,
                "write-bytes":11927552,
                "write-bytes-complete":true,
                "read-records":185139,
                "read-records-complete":true,
                "write-records":133880,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0.125,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0.1,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        },
        {
            "id":"f8543e3639e7b3e505fe052f4d476c57",
            "name":"LeftOuterJoin(where: (=(id, student_id)), join: (id, phone_number, creat_time, status, customer_id, spread_source, remark_name, student_id, assistant_id)) -> Calc(select: (id AS user_id, phone_number AS body.phone_num, creat_time AS body.create_time, status AS body.status, customer_id AS body.customer_id, spread_source AS body.spread_source, remark_name AS body.remark_name, assistant_id AS body.assistant_id)) -> SinkConversion to Tuple2 -> Sink: HBase143Writer-> table:flink:olap_rt_student_real_time_static_test schema:{HBaseTableSchemaV2{ rowKeyName='user_id', rowKeyType=Long, charset=UTF-8, familySchema=body:phone_num|String, body:create_time|Timestamp, body:status|Integer, body:customer_id|Long, body:spread_source|String, body:remark_name|String, body:assistant_id|String}}",
            "parallelism":1,
            "status":"RUNNING",
            "start-time":1560934281605,
            "end-time":-1,
            "duration":78613499,
            "tasks":{
                "CREATED":0,
                "CANCELING":0,
                "DEPLOYING":0,
                "FINISHED":0,
                "RECONCILING":0,
                "FAILED":0,
                "SCHEDULED":0,
                "CANCELED":0,
                "RUNNING":1
            },
            "metrics":{
                "read-bytes":13196263,
                "read-bytes-complete":true,
                "write-bytes":0,
                "write-bytes-complete":true,
                "read-records":172261,
                "read-records-complete":true,
                "write-records":0,
                "write-records-complete":true,
                "buffers-in-pool-usage-max":0.125,
                "buffers-in-pool-usage-max-complete":true,
                "buffers-out-pool-usage-max":0,
                "buffers-out-pool-usage-max-complete":true,
                "tps":0,
                "tps-complete":true,
                "delay":-1,
                "delay-complete":true
            }
        }
    ],
    "status-counts":{
        "CREATED":0,
        "CANCELING":0,
        "DEPLOYING":0,
        "FINISHED":0,
        "RECONCILING":0,
        "FAILED":0,
        "SCHEDULED":0,
        "CANCELED":0,
        "RUNNING":6
    },
    "plan":{
        "jid":"40d2c6dbe0d579018698c7e20e6ace1e",
        "name":"olap_rt_student_real_time_static_test",
        "nodes":[
            {
                "id":"cbc357ccb763df2852fee8c4fc7d55f2",
                "parallelism":1,
                "operator":"",
                "operator_strategy":"",
                "description":"Source: UmsKafka010TableSource(creat_time, spread_source, last_update_time, phone_number, id, status) -> SourceConversion(table:[builtin, default, t_user_info, source: [UmsKafka010TableSource(creat_time, spread_source, last_update_time, phone_number, id, status)]], fields:(creat_time, spread_source, last_update_time, phone_number, id, status)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(select: (id, phone_number, creat_time, status))",
                "optimizer_properties":{

                }
            },
            {
                "id":"6cdc5bb954874d922eaee11a8e7b5dd5",
                "parallelism":1,
                "operator":"",
                "operator_strategy":"",
                "description":"Source: UmsKafka010TableSource(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id) -> SourceConversion(table:[builtin, default, t_customer_info, source: [UmsKafka010TableSource(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id)]], fields:(is_deleted, create_time, spread_source, last_update_time, user_id, remark_name, customer_id)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(where: ((CAST(is_deleted) = 0) AND user_id IS NOT NULL), select: (user_id, customer_id, spread_source, remark_name))",
                "optimizer_properties":{

                }
            },
            {
                "id":"2963852293169ba90d9d1e7d6308db5c",
                "parallelism":1,
                "operator":"",
                "operator_strategy":"",
                "description":"Source: UmsKafka010TableSource(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id) -> SourceConversion(table:[builtin, default, t_customer_assistant_relation, source: [UmsKafka010TableSource(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id)]], fields:(last_update_time, assistant_id, is_deleted, create_time, student_id, customer_id, assistant_city_id)) -> WatermarkAssigner(rowtime: last_update_time, offset: 4000) -> Calc(where: ((CAST(is_deleted) = 0) AND student_id IS NOT NULL), select: (student_id, CAST(assistant_id) AS assistant_id))",
                "optimizer_properties":{

                }
            },
            {
                "id":"edff7340c63af0cafbf43d7dda52199d",
                "parallelism":1,
                "operator":"",
                "operator_strategy":"",
                "description":"GroupAggregate(groupBy: (user_id, customer_id), select: (user_id, customer_id, MAX(spread_source) AS spread_source, MAX(remark_name) AS remark_name))",
                "inputs":[
                    {
                        "num":0,
                        "id":"6cdc5bb954874d922eaee11a8e7b5dd5",
                        "ship_strategy":"HASH",
                        "exchange":"pipelined"
                    }
                ],
                "optimizer_properties":{

                }
            },
            {
                "id":"dc84cce8187b24c5fc99ebc698f3e3f7",
                "parallelism":1,
                "operator":"",
                "operator_strategy":"",
                "description":"LeftOuterJoin(where: (=(id, user_id)), join: (id, phone_number, creat_time, status, user_id, customer_id, spread_source, remark_name)) -> Calc(select: (id, phone_number, creat_time, status, customer_id, spread_source, remark_name))",
                "inputs":[
                    {
                        "num":0,
                        "id":"cbc357ccb763df2852fee8c4fc7d55f2",
                        "ship_strategy":"HASH",
                        "exchange":"pipelined"
                    },
                    {
                        "num":1,
                        "id":"edff7340c63af0cafbf43d7dda52199d",
                        "ship_strategy":"HASH",
                        "exchange":"pipelined"
                    }
                ],
                "optimizer_properties":{

                }
            },
            {
                "id":"f8543e3639e7b3e505fe052f4d476c57",
                "parallelism":1,
                "operator":"",
                "operator_strategy":"",
                "description":"LeftOuterJoin(where: (=(id, student_id)), join: (id, phone_number, creat_time, status, customer_id, spread_source, remark_name, student_id, assistant_id)) -> Calc(select: (id AS user_id, phone_number AS body.phone_num, creat_time AS body.create_time, status AS body.status, customer_id AS body.customer_id, spread_source AS body.spread_source, remark_name AS body.remark_name, assistant_id AS body.assistant_id)) -> SinkConversion to Tuple2 -> Sink: HBase143Writer-> table:flink:olap_rt_student_real_time_static_test schema:{HBaseTableSchemaV2{ rowKeyName='user_id', rowKeyType=Long, charset=UTF-8, familySchema=body:phone_num|String, body:create_time|Timestamp, body:status|Integer, body:customer_id|Long, body:spread_source|String, body:remark_name|String, body:assistant_id|String}}",
                "inputs":[
                    {
                        "num":0,
                        "id":"dc84cce8187b24c5fc99ebc698f3e3f7",
                        "ship_strategy":"HASH",
                        "exchange":"pipelined"
                    },
                    {
                        "num":1,
                        "id":"2963852293169ba90d9d1e7d6308db5c",
                        "ship_strategy":"HASH",
                        "exchange":"pipelined"
                    }
                ],
                "optimizer_properties":{

                }
            }
        ]
    }
}
render(
  <Provider store={store}>
    <FlinkGraph jobDetailCorrect={jobDetailCorrect}/>
  </Provider>,
  document.getElementById('root')
)